#!/bin/bash

_find_bash_config() {
    if [[ -f ~/.bash_profile ]]; then echo "$HOME/.bash_profile";
    else echo "$HOME/.bashrc"; fi
}

install() {
    if [[ ! -d ~/.script_kitty ]]; then
	mkdir ~/.script_kitty
    fi
    conf=$(_find_bash_config)
    if $(grep -qv "SCRIPT_KITTY_MAGIC_YARNBALL" $conf); then
	KITTY_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
	echo "## SCRIPT_KITTY_MAGIC_YARNBALL ##" >> $conf
	read -p "Kitty needs a github: " ghuser
	touch "$KITTY_HOME/.kittens"
	for yarnball in $(cat "$KITTY_HOME/.kittens"); do
	    echo $yarnball
	done
    fi
}

install
